version: 2.1
_definitions:
  - &semver_pattern /^\d+\.\d+\.\d+.*/
executors:
  python:
    docker:
      - image: cimg/python:3.12.1
jobs:
  test-python:
    executor: python
    steps:
      - checkout
      - run:
          name: Install uv
          command: pip install uv
      - run:
          name: Install dependencies
          command: uv sync --locked
      - run:
          name: Check style
          command: uv run black --check .
      - run:
          name: Run tests
          command: |
            uv run coverage run --source jinjabread -m unittest discover .
            uv run coverage report
            uv run coverage html
      - store_artifacts:
          path: htmlcov
  publish-python-package:
    executor: python
    steps:
      - checkout
      - run:
          name: Install uv
          command: pip install uv
      - run:
          name: Create build
          command: uv build
      - run:
          name: Upload build
          command: uvx twine upload dist/*
workflows:
  main:
    jobs:
      - test-python:
          filters:
            tags:
              only: *semver_pattern
      - publish-python-package:
          context:
            - jinjabread-prod
          requires:
            - test-python
          filters:
            tags:
              only: *semver_pattern
            branches:
              ignore: /.*/
